### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Dr-Wacko** [keksexception/LobbyNPCs#3]
**Describe the bug**
After I enter the name of the npc it says to "Fetch the NPCs uuid <npc name> (that enables cape)? I then have no option to press yes or no which is shown in the video.

**To Reproduce**
1. Make it so I dont have this problem
2. 
3. 
4. 

**Expected behavior**
I expected to be able to press no when this happens

**Console log**
If applicable, add the console log with the error to help explain your problem.

**Desktop (please complete the following information):**
 - Pluginversion [e.g. 1.0-b1]
 - PluginLib version [e.g. 1.1-b1]
 - Server version [e.g. 1.8.8]
 - Java version [e.g. Java 8]

**Additional context**
Please fix it. This is like the only bungeecord npc plugin out there that I can find other than BungeeNPCs which I do not feel like paying $10 for.

**Comment by keksexception** [comment]
Which server version do you use?
Please enter /lobbynpc info and send a screenshot of the message that appear :D
