### ISSUE TITLE
another 1.15.2 Bug

### ISSUE THREAD

**Issue by Jachimoo** [keksexception/LobbyNPCs#5]
**Describe the bug**
When I restart server the NPC are gone 

**To Reproduce**
1. Setup NPC's at 1.15.2
2. Restart server
3. Pufff... the Npc's are gone
4. 

**Console log**
Normal log but nps not working

info:**
 - Pluginversion 1.1-r3
 - PluginLib version 1.1-b4
 - Server version 1.15.2 Paper
 - Java version Java 8

**Installed plugins**
DeluxeHub
EasyPrefix
EssentialsX
LoginSecurity
LuckPerms
PlaceholderApi
PluginConstructorApi
ViaVersions
Worldedit
worldguard
WorldeditselectionVisualizer
Ajparkour

**Additional context**

**Comment by Jachimoo** [comment]
PS.
In npcdata.yml seems save all data

**Comment by Jachimoo** [comment]
Probably something with npcdata.dat

**Comment by keksexception** [comment]
Try to delete npcdata.yml and npcdata.dat (stop the server before). Then recreate the NPC. 
Is the error still there?

**Comment by Jachimoo** [comment]
I see the problem here... I think that if you use command /reload ,/reload confirm the information about NPC are not saving and If you are stoping the server that information will be saved.
Problem solved.. I think

but In my opinion you should fix that. I mean If someone is using command to reload server like me then information about NPC have to be saved
