### ISSUE TITLE
Setup not working [BUG]

### ISSUE THREAD

**Issue by TheNotTanMan** [keksexception/LobbyNPCs#7]
**Describe the bug**
When it asks me "Sneak when others sneak" and I try to press yes or no neither of them work. It won't go to the next question and therefore I can create a npc.

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**

**Console log**
If applicable, add the console log with the error to help explain your problem.

**Please complete the following information or send the information displayed by typing /lobbynpc info:**
 - Pluginversion [e.g. 1.0-b1]
 - PluginLib version [e.g. 1.1-b1]
 - Server version [e.g. 1.8]
 - Java version [e.g. Java 8]

**Installed plugins**
Mutechat, Worldedit, Worldguard, 9Spawn, Flyspeed, XoroDisguise, PlaceholderAPI, fly, invsee, FriendSystem, LobbyNpc, EasyPrefix, Multiverse-Core, PluginLib, Scoreboard-revision

**Additional context**

**Comment by keksexception** [comment]
Hi, 
you are using old versions of LobbyNPC (1.0-b1 newest: 1.1-r3) and PluginLib (1.1-b1 newest 1.1-b4). Please download the newest updates. If the problem persists, try to install [the labymod server API](https://www.spigotmc.org/resources/labymod-server-api.52423/).

**Comment by TheNotTanMan** [comment]
Hi! I did the thing wrong and I was on the newest version in the first place. So I download the plugin you said to download and it fixed the problem but I have another problem now. Instead of sneak when players sneak it's the same thing with Play random emote when forcefield is triggered. Nothing happens when I press yes or no.

**Comment by keksexception** [comment]
Which server version are you using? Is there any error in console?

**Comment by TheNotTanMan** [comment]
The server version when I do /lobbynpc info is git-Spigot-13716d9-0899683 (MC: 1.8) The things in the console are right here org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot19.jar:git-Spigot-13716d9-0899683] org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot19.jar:git-Spigot-13716d9-0899683] org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot19.jar:git-Spigot-13716d9-0899683] org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot19.jar:git-Spigot-13716d9-0899683] net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1107) [spigot19.jar:git-Spigot-13716d9-0899683] net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot19.jar:git-Spigot-13716d9-0899683]
net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot19.jar:git-Spigot-13716d9-0899683] at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot19.jar:git-Spigot-13716d9-0899683] 
at
net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot19.jar:git-Spigot-13716d9-0899683]
at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot19.jar:git-Spigot-13716d9-0899683] at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot19.jar:git-Spigot-13716d9-0899683]
at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot19.jar:git-Spigot-13716d9-0899683] 
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
Caused by: java.lang.NullPointerException
at de.raffi.pluginlib.npc.NPC.<init>(NPC.java:44) ~[?:?]
at de.raffi.pluginlib.npc.NPC.<init>(NPC.java:54) ~[?:?]
at de.raffi.lobbynpcs.commands.LobbyNPCCommand.createNPC(LobbyNPCCommand.java:323) ~[?:?]
12.06 15:05:58 [Server] INFO at 
de.raffi.lobbynpcs.commands.LobbyNPCCommand$1$1$1$1$1$1$1$1$1$1$1.onHandlerRemoved(LobbyNPCCommand.java:111) ~[?:?]
at de.raffi.pluginlib.test.InputHandler.onCommand(InputHandler.java:53) ~[?:?]
at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_211]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_211]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot19.jar:git-Spigot-13716d9-089968

**Comment by keksexception** [comment]
It seems like you are using a too old version of spigot (v1_8_R1 newest v1_8_R3). Please download the latest spigot 1.8 version.

**Comment by TheNotTanMan** [comment]
How would I get the newest version? Would I have to upgrade to 1.8.8?

**Comment by keksexception** [comment]
Yes

**Comment by TheNotTanMan** [comment]
It kicked me out when I did "Play random emote when forcefield is triggered" 
![image](https://user-images.githubusercontent.com/66755448/84580388-8a044980-ada4-11ea-930e-8b37171785cb.png)

**Comment by TheNotTanMan** [comment]
and now it won't let me in the server. I tried to redownload it and now I can't even have it without getting kicked. Is there anything I can do?

**Comment by keksexception** [comment]
1. Stop Server
2. Delete npcdata.dat and npcdata.yml
3. Start server
