### ISSUE TITLE
Commands not having any effect

### ISSUE THREAD

**Issue by NerdGamerBoiYT** [keksexception/LobbyNPCs#8]
The command prompt shows up in the chat, however, /lobbynpc create has no effect whatsoever

1. I downloaded PluginLib and LobbyNPCs
2. I restarted the server
3. I opened up Minecraft and connected to my server
4. I tried the command, and the prompt showed up, but when I pressed enter, it did not have any effect in the chat or in the world

I expected the usual questions in the chat to show up that deal with customizing my npc.

There is no error message as far as I can tell

 - 1.1-r3
 - 1.1-b4
 - 1.14.4
 - Java 8

AntiCheatReloaded
ScreamingBedwars
ChatControl
Dynmap
LobbyNPCs
LuckPerms
Multiverse Core
Multiverse Portals
NoCussing
PluginLib
ProtocolLib
Vault
bPermissions
MyWarp
WorldEdit
WorldGuard

**Comment by keksexception** [comment]
Plugin worked fine when i tested it on 1.14.4 ... One of your plugins might block the /lobbynpc command. 
The following steps may solve the problem:
1. Stop server
2. Delete LobbyNPCs folder
3. Start server
4. If the problem persists, try to remove all plugins exept PluginLib and LobbyNPCs and try the /lobbynpc create command again in minecraft
